apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: adguardhome
spec:
  values:
    ingress:
      enabled: true
      ingressClassName: traefik
      hosts:
        - host: agh.staging.kindlabz.xyz
          paths:
            - path: /
              pathType: ImplementationSpecific
              backend:
                service:
                  port:
                    name: http
    persistence:
      storageClass: staging-storage
