apiVersion: v1
data:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:3SBXK8XZpRCi4fv75KrZe56ak6Xbb2sXy4KdIbK7CKCeobuZSNcP5NO3dieC5JmFQ3txrH9S5i4=,iv:KVe9JLoDUKSw8PwOQciCNjpBgCX3UWBqAUO3WTrpxfs=,tag:iDU/uYQjFsIeDL9D9qNhwg==,type:str]
kind: Secret
metadata:
    name: renovate-container-env
sops:
    age:
        - recipient: age1p7wtna2utvyvqlnqyk5r7wwexsrldlktd2vg40e9kcz0u4hstq8ste6se2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0NlhpVzVleTVSeUZWWFFI
            VGRoYzNLLzNmTWx4Rk1iK2tCUVNhamtxNTJjClZWWFZPWkRJQkczN0dmdFhOdGVu
            aENGUDRlL3R0b2RRNXliOExRVnlOMFUKLS0tIHdaaCtsbGgzL25wd21OS01IMUxD
            cVdRMTRrYlZWVVY4bS9TSjZpb3Z6bFEKO1gRgC2Rgr3Y1KcaMLuLja33X1kv7gPl
            OQyh8ryPRQaMvMN4RNNSaNTkw7ARTMUBYlih+gKTaWan0ohPoo1EeA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T09:17:07Z"
    mac: ENC[AES256_GCM,data:yXssjP0yRNdlPyTa6NJDjFv9PZPAxRHoM4euT7Qs4a7dsdHcJPIF1CjP5vCqsCqa1lc/6UTHfC0sio7awQ9hSog3PLkQ3wbBIzcQf6ZUqUB6LoCgrt5FcmadsRPtXAK3Od0TybIf+0J5N/ZW9k0jZ7E4zFDrqOMtxQdtR1VHTY4=,iv:2XTpOR2UpyBl4PeFgMSyPSDpuI4M/mAvhjFBo0ocQrg=,tag:qE74kgP9BtVgFxLXo6DT4g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.0
