apiVersion: apps/v1
kind: Deployment
metadata:
  name: audiobookshelf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audiobookshelf
  template:
    metadata:
      labels:
        app: audiobookshelf
    spec:
      securityContext:
        fsGroup: 33 # www-data group ID
        runAsUser: 33 # www-data user ID
        runAsGroup: 33 # www-data group ID
      containers:
        - name: audiobookshelf
          image: advplyr/audiobookshelf:latest
          ports:
            - containerPort: 13378
          securityContext: 
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: audiobookshelf-data
              mountPath: /audiobooks
            - name: audiobookshelf-data
              mountPath: /podcasts
            - name: audiobookshelf-data
              mountPath: /config
            - name: audiobookshelf-data
              mountPath: /metadata
      volumes:
        - name: audiobookshelf-data
          persistentVolumeClaim:
            claimName: audiobookshelf-data-pvc
