apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging-adguardhome
resources:
  - ../../base/adguardhome/
patches:
  - path: patches/namespace.yaml
    target:
      kind: Namespace
      name: adguardhome
  - path: patches/release.yaml 
    target:
      kind: HelmRelease
      name: adguardhome
