apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: linkding-staging
resources:
#  - ../../base/linkding/
#  - linkding-container-env-secret.yaml
#  - ingress.yaml
#patches:
#  - path: namespace.yaml
#    target:
#      kind: namespace
#      name: linkding
#  - path: storage.yaml
#    target:
#      name: PersistentVolumeClaim
#      name: linkding-data-pvc
