apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: linkding-staging
resources:
  - ../../base/linkding/
  - resources/linkding-container-env-secret.yaml
  - resources/ingress.yaml
patches:
  - path: patches/namespace.yaml
    target:
      kind: namespace
      name: linkding
  - path: patches/storage.yaml
    target:
      name: PersistentVolumeClaim
      name: linkding-data-pvc
