apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: homevault-staging
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: cluster.local/nfs-subdir-external-provisioner
parameters:
  server: 192.168.68.63
  path: /volume1/k8s/staging
  pathPattern: "${.PVC.namespace}/${.PVC.name}"
  onDelete: retain
reclaimPolicy: Retain
volumeBindingMode: Immediate
