apiVersion: v1
data:
    values.yaml: ENC[AES256_GCM,data:KZoZh8DsowX5IKMVCV4aokWwK3WdW44OyWkhQFY4eKemS3e90Sz+++QczQwoxtqBMXc0X8uamLxTsxGG6KmltA==,iv:IJk8QO6EVmAgAwTv/A42THovcvVuOcjP+jqYoBmN3Jk=,tag:ZfqNcdviqjoJRh78EF04sQ==,type:str]
kind: Secret
metadata:
    name: kube-prometheus-stack-values
    namespace: homevault
sops:
    age:
        - recipient: age1p7wtna2utvyvqlnqyk5r7wwexsrldlktd2vg40e9kcz0u4hstq8ste6se2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0Syt0Ky9pZlY2dVBGbFpo
            STdUTVNDN3pOTXVqUlB0S3ZMYURLaENMdndrCi9SNWtOdGRzZ2FRZWNMN1RjU3JY
            cVpVMko0NUtnb1FOdTNkdzdZSU85WE0KLS0tIDN2VkZoK3oyUnVZQWRwYjN4K0sv
            Wnh3VnhCTHF2NTkzSE9jcWlpbFV0WG8Khitc8xfnMTKvcrhBpcDjTWdRv5Z2feVi
            xqmoMfK6ua4R51l58ZrIZatYbsTrIhklcmNu+m7zvHwrOlPq3Dk5dg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-17T19:03:56Z"
    mac: ENC[AES256_GCM,data:M1gF7hlvkzM9X2IHwBqc426dFTPHVhYd3OI00MlrEWvClytvcM0io3r3yGt0PSwDg7XTCUPOauwvsxlM8UYVkccfGw7elXqPoqEwlCAth7EA8x+v/sfD/X2WUrBycUreJ4xHU45cY/StWe1M4bUtlE9dd56RCb8/7UseJ0DeQ4I=,iv:suDPtsu2h+SnKp3bBtVkIDI6WSrlExZiLFV8ubLaLoE=,tag:MxBaoHSOt5Y4qsiigPlpRw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
