apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-config-pvc
  namespace: adguard
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
    storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-data-pvc
  namespace: adguard
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
    storage: 5Gi
