apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: storage-staging
resources:
  - ../../base/nfs-provisioner/
  - resources/storageclass.yaml
patches:
  - path: patches/namespace.yaml
    target: 
      kind: Namespace
      name: storage
  - path: patches/release.yaml
    target:
      kind: HelmRelease
      name: nfs-provisioner
